# Generated by Django 4.1.3 on 2022-11-21 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, default='signature.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='signature',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('body', models.TextField(blank=True)),
                ('value', models.TextField(choices=[('valid', 'Valid'), ('unvalid', 'Unvalid')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('signature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='signatures.signature')),
            ],
        ),
        migrations.AddField(
            model_name='signature',
            name='tags',
            field=models.ManyToManyField(blank=True, to='signatures.tag'),
        ),
    ]
