# Generated by Django 4.1.3 on 2022-11-25 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_verify_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
