# Generated by Django 4.1.3 on 2022-11-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_personal_signature_and_more'),
        ('signatures', '0009_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.TextField(choices=[('valid', 'Valid'), ('Invalid', 'Invalid')]),
        ),
    ]
