# Generated by Django 4.1.3 on 2022-11-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_github_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_signature',
            field=models.ImageField(blank=True, default='signatures/default.png', upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/avatar.png', upload_to='profiles/'),
        ),
    ]
