# Generated by Django 4.1.3 on 2022-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_personal_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_signature',
            field=models.ImageField(blank=True, default='signatures/default.png', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
