# Generated by Django 4.1.3 on 2022-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_project_description_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='positive_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
